### ISSUE TITLE
Processing large image planes fails silently

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-omero#34]
When attempting to run Find Edges on a 19000x19000 single-plane image, @pwalczysko noticed that it failed, but without any meaningful error message.

**Comment by ctrueden** [comment]
I uploaded a 32-bit 19100x19200 image to OMERO via the command line importer. 20 minutes later, OMERO.web still shows "No image" with no thumbnail, and CPU doesn't seem to be doing anything.

When attempting to open the image in ImageJ via File > Import > OMERO..., the following exception occurred:
```
[ERROR] Module threw exception
java.lang.ArrayIndexOutOfBoundsException: null
	at java.lang.System.arraycopy(Native Method) ~[na:1.8.0_11]
	at io.scif.util.ImageTools.splitChannels(ImageTools.java:237) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.filters.PlaneSeparator.openPlane(PlaneSeparator.java:322) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.filters.PlaneSeparator.openPlane(PlaneSeparator.java:208) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.filters.AbstractReaderFilter.openPlane(AbstractReaderFilter.java:225) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.filters.AbstractReaderFilter.openPlane(AbstractReaderFilter.java:191) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.img.cell.loaders.AbstractArrayLoader.read(AbstractArrayLoader.java:224) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.img.cell.loaders.AbstractArrayLoader.read(AbstractArrayLoader.java:196) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.img.cell.loaders.AbstractArrayLoader.loadArray(AbstractArrayLoader.java:173) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.img.cell.SCIFIOCellCache.load(SCIFIOCellCache.java:147) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.img.cell.SCIFIOImgCells$CachedCells.get(SCIFIOImgCells.java:122) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.img.cell.SCIFIOImgCells$CachedCells.get(SCIFIOImgCells.java:101) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at net.imglib2.img.list.ListCursor.get(ListCursor.java:81) ~[imglib2-2.2.1.jar:2.2.1]
	at net.imglib2.img.cell.CellCursor.getCell(CellCursor.java:93) ~[imglib2-2.2.1.jar:2.2.1]
	at net.imglib2.img.cell.CellCursor.moveToNextCell(CellCursor.java:181) ~[imglib2-2.2.1.jar:2.2.1]
	at net.imglib2.img.cell.CellCursor.reset(CellCursor.java:151) ~[imglib2-2.2.1.jar:2.2.1]
	at net.imglib2.img.cell.CellCursor.<init>(CellCursor.java:87) ~[imglib2-2.2.1.jar:2.2.1]
	at net.imglib2.img.cell.AbstractCellImg.cursor(AbstractCellImg.java:114) ~[imglib2-2.2.1.jar:2.2.1]
	at net.imglib2.img.cell.AbstractCellImg.cursor(AbstractCellImg.java:48) ~[imglib2-2.2.1.jar:2.2.1]
	at net.imglib2.img.AbstractImg.firstElement(AbstractImg.java:82) ~[imglib2-2.2.1.jar:2.2.1]
	at net.imagej.ImgPlus.firstElement(ImgPlus.java:261) ~[imagej-common-0.14.0.jar:2.0.0-rc-30]
	at net.imagej.DefaultDataset.getType(DefaultDataset.java:231) ~[imagej-common-0.14.0.jar:2.0.0-rc-30]
	at net.imagej.DefaultDataset.isSigned(DefaultDataset.java:236) ~[imagej-common-0.14.0.jar:2.0.0-rc-30]
	at net.imagej.DefaultDataset.mergedColorCompatible(DefaultDataset.java:719) ~[imagej-common-0.14.0.jar:2.0.0-rc-30]
	at net.imagej.DefaultDataset.<init>(DefaultDataset.java:101) ~[imagej-common-0.14.0.jar:2.0.0-rc-30]
	at net.imagej.DefaultDatasetService.create(DefaultDatasetService.java:195) ~[imagej-common-0.14.0.jar:2.0.0-rc-30]
	at io.scif.services.SCIFIODatasetService.create(SCIFIODatasetService.java:143) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:127) ~[scifio-0.23.1-SNAPSHOT.jar:0.23.1-SNAPSHOT]
	at net.imagej.omero.commands.OpenImageFromOMERO.run(OpenImageFromOMERO.java:80) ~[imagej-omero-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at org.scijava.command.CommandModule.run(CommandModule.java:201) ~[scijava-common-2.41.1-SNAPSHOT.jar:2.41.1-SNAPSHOT]
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167) [scijava-common-2.41.1-SNAPSHOT.jar:2.41.1-SNAPSHOT]
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126) [scijava-common-2.41.1-SNAPSHOT.jar:2.41.1-SNAPSHOT]
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65) [scijava-common-2.41.1-SNAPSHOT.jar:2.41.1-SNAPSHOT]
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:181) [scijava-common-2.41.1-SNAPSHOT.jar:2.41.1-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_11]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]
```
Pushing to a later milestone, since there will be a number of challenges with big images, and they are a less common initial use case. Once support for large image planes is further along in ImageJ (see e.g. imagej/imagej#87, scifio/scifio#125, imagej/imagej-common#13).
