### ISSUE TITLE
FindEdges bugs out with multicolour and/or multi t/z images

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-omero#47]
From @pwalczysko:
> ran "Find edges" from Insight (insight was RC3) - the image ID was pre-populated in the script window as expected. The new image was created in Orphaned folder as expected. Nevertheless, an error appears in Activities.
> ```
> [ERROR] Exception
> java.io.IOException: io.scif.img.ImgIOException: io.scif.FormatException: Error writing to OMERO: imageIndex=0, planeIndex=1
>     at net.imagej.DefaultDatasetService.save(DefaultDatasetService.java:308) ~[imagej-common-0.8.0.jar:2.0.0-rc-9]
>     at net.imagej.DefaultDatasetService.save(DefaultDatasetService.java:292) ~[imagej-common-0.8.0.jar:2.0.0-rc-9]
>     at net.imagej.omero.DefaultOMEROService.uploadImage(DefaultOMEROService.java:343) ~[imagej-omero-0.1.0.jar:0.1.0]
>     at net.imagej.omero.DefaultOMEROService.toOMERO(DefaultOMEROService.java:224) ~[imagej-omero-0.1.0.jar:0.1.0]
>     at net.imagej.omero.DefaultOMEROService.toOMERO(DefaultOMEROService.java:235) ~[imagej-omero-0.1.0.jar:0.1.0]
>     at net.imagej.omero.ModuleAdapter.launch(ModuleAdapter.java:138) ~[imagej-omero-0.1.0.jar:0.1.0]
>     at net.imagej.omero.ScriptRunner.invoke(ScriptRunner.java:91) [imagej-omero-0.1.0.jar:0.1.0]
>     at net.imagej.omero.ScriptRunner.invoke(ScriptRunner.java:74) [imagej-omero-0.1.0.jar:0.1.0]
>     at net.imagej.omero.ScriptRunner.main(ScriptRunner.java:116) [imagej-omero-0.1.0.jar:0.1.0]
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_65]
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_65]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_65]
>     at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_65]
>     at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:258) [imagej-launcher-3.1.1.jar:3.1.1]
>     at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:184) [imagej-launcher-3.1.1.jar:3.1.1]
>     at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:76) [imagej-launcher-3.1.1.jar:3.1.1]
> Caused by: io.scif.img.ImgIOException: io.scif.FormatException: Error writing to OMERO: imageIndex=0, planeIndex=1
>     at io.scif.img.ImgSaver.writePlanes(ImgSaver.java:655) ~[scifio-0.15.4.jar:0.15.4]
>     at io.scif.img.ImgSaver.writeImg(ImgSaver.java:516) ~[scifio-0.15.4.jar:0.15.4]
>     at io.scif.img.ImgSaver.writeImg(ImgSaver.java:502) ~[scifio-0.15.4.jar:0.15.4]
>     at io.scif.img.ImgSaver.writeImg(ImgSaver.java:472) ~[scifio-0.15.4.jar:0.15.4]
>     at io.scif.img.ImgSaver.writeImg(ImgSaver.java:452) ~[scifio-0.15.4.jar:0.15.4]
>     at io.scif.img.ImgSaver.saveImg(ImgSaver.java:157) ~[scifio-0.15.4.jar:0.15.4]
>     at io.scif.img.ImgSaver.saveImg(ImgSaver.java:141) ~[scifio-0.15.4.jar:0.15.4]
>     at net.imagej.DefaultDatasetService.save(DefaultDatasetService.java:305) ~[imagej-common-0.8.0.jar:2.0.0-rc-9]
>     ... 15 common frames omitted
> Caused by: io.scif.FormatException: Error writing to OMERO: imageIndex=0, planeIndex=1
>     at io.scif.omero.OMEROFormat.writerException(OMEROFormat.java:635) ~[scifio-omero-0.5.1.jar:0.5.1]
>     at io.scif.omero.OMEROFormat.access$300(OMEROFormat.java:73) ~[scifio-omero-0.5.1.jar:0.5.1]
>     at io.scif.omero.OMEROFormat$Writer.writePlane(OMEROFormat.java:512) ~[scifio-omero-0.5.1.jar:0.5.1]
>     at io.scif.AbstractWriter.savePlane(AbstractWriter.java:168) ~[scifio-0.15.4.jar:0.15.4]
>     at io.scif.AbstractWriter.savePlane(AbstractWriter.java:159) ~[scifio-0.15.4.jar:0.15.4]
>     at io.scif.img.ImgSaver.writePlanes(ImgSaver.java:652) ~[scifio-0.15.4.jar:0.15.4]
>     ... 22 common frames omitted
> Caused by: omero.ApiUsageException: null
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_65]
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[na:1.6.0_65]
>     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[na:1.6.0_65]
>     at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[na:1.6.0_65]
>     at java.lang.Class.newInstance0(Class.java:357) ~[na:1.6.0_65]
>     at java.lang.Class.newInstance(Class.java:310) ~[na:1.6.0_65]
>     at IceInternal.BasicStream.createUserException(BasicStream.java:2615) ~[omero-client-dev_5_0-ice35-b287.jar:na]
>     at IceInternal.BasicStream.access$300(BasicStream.java:12) ~[omero-client-dev_5_0-ice35-b287.jar:na]
>     at IceInternal.BasicStream$EncapsDecoder10.throwException(BasicStream.java:3099) ~[omero-client-dev_5_0-ice35-b287.jar:na]
>     at IceInternal.BasicStream.throwException(BasicStream.java:2077) ~[omero-client-dev_5_0-ice35-b287.jar:na]
>     at IceInternal.Outgoing.throwUserException(Outgoing.java:538) ~[omero-client-dev_5_0-ice35-b287.jar:na]
>     at omero.api._RawPixelsStoreDelM.setPlane(_RawPixelsStoreDelM.java:1668) ~[omero-client-dev_5_0-ice35-b287.jar:na]
>     at omero.api.RawPixelsStorePrxHelper.setPlane(RawPixelsStorePrxHelper.java:8082) ~[omero-client-dev_5_0-ice35-b287.jar:na]
>     at omero.api.RawPixelsStorePrxHelper.setPlane(RawPixelsStorePrxHelper.java:8044) ~[omero-client-dev_5_0-ice35-b287.jar:na]
>     at io.scif.omero.OMEROFormat$Writer.writePlane(OMEROFormat.java:509) ~[scifio-omero-0.5.1.jar:0.5.1]
>     ... 25 common frames omitted
> ```
> It seems that the error above is specific to running the script on multicolour and or multi t/z images. When the script was run at a simple black/white single plane image, no error occurred.

See also the original bug report at https://github.com/openmicroscopy/openmicroscopy/pull/2391#issuecomment-50741042.

**Comment by ctrueden** [comment]
This is probably a duplicate of #55.
