### ISSUE TITLE
Images from Screen/Plate/Well do not download properly

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-omero#86]
```
Exception in thread "SciJava-7c79bd9b-Thread-11" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:32)
	at net.imglib2.img.cell.LazyCellImg$LazyCells.get(LazyCellImg.java:104)
	at net.imglib2.img.list.AbstractLongListImg$LongListRandomAccess.get(AbstractLongListImg.java:274)
	at net.imglib2.img.cell.CellRandomAccess.getCell(CellRandomAccess.java:136)
	at net.imglib2.img.cell.CellRandomAccess.updatePosition(CellRandomAccess.java:474)
	at net.imglib2.img.cell.CellRandomAccess.setPosition(CellRandomAccess.java:437)
	at net.imglib2.view.RandomAccessibleIntervalCursor.jumpFwd(RandomAccessibleIntervalCursor.java:106)
	at net.imagej.minmax.DefaultMinMaxMethod.compute(DefaultMinMaxMethod.java:222)
	at net.imagej.minmax.DefaultMinMaxMethod$1.run(DefaultMinMaxMethod.java:180)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at net.imglib2.cache.ref.SoftRefLoaderRemoverCache.get(SoftRefLoaderRemoverCache.java:168)
	at net.imglib2.cache.util.LoaderRemoverCacheAsLoaderCacheAdapter.get(LoaderRemoverCacheAsLoaderCacheAdapter.java:37)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:28)
	... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at io.scif.util.ImageTools.splitChannels(ImageTools.java:237)
	at io.scif.filters.PlaneSeparator.openPlane(PlaneSeparator.java:321)
	at io.scif.filters.PlaneSeparator.openPlane(PlaneSeparator.java:207)
	at io.scif.filters.AbstractReaderFilter.openPlane(AbstractReaderFilter.java:224)
	at io.scif.filters.AbstractReaderFilter.openPlane(AbstractReaderFilter.java:190)
	at io.scif.img.cell.loaders.AbstractArrayLoader.read(AbstractArrayLoader.java:289)
	at io.scif.img.cell.loaders.AbstractArrayLoader.read(AbstractArrayLoader.java:271)
	at io.scif.img.cell.loaders.AbstractArrayLoader.read(AbstractArrayLoader.java:253)
	at io.scif.img.cell.loaders.AbstractArrayLoader.loadArray(AbstractArrayLoader.java:232)
	at io.scif.img.cell.SCIFIOCellImgFactory$SCIFIOCellLoader.load(SCIFIOCellImgFactory.java:204)
	at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:91)
	at net.imglib2.cache.img.LoadedCellCacheLoader.get(LoadedCellCacheLoader.java:51)
	at net.imglib2.cache.img.DiskCellCache.get(DiskCellCache.java:104)
	at net.imglib2.cache.img.DiskCellCache.get(DiskCellCache.java:43)
	at net.imglib2.cache.IoSync.get(IoSync.java:174)
	at net.imglib2.cache.ref.SoftRefLoaderRemoverCache.get(SoftRefLoaderRemoverCache.java:158)
	... 12 more
```
To reproduce, need to attempt to access an image ID from an SPW acquisition.

**Comment by jburel** [comment]
The error looks similar to https://github.com/imagej/imagej-omero/issues/92
I have opened successfully an image from an HTD plate
