### ISSUE TITLE
SVS file

### ISSUE THREAD

**Issue by jburel** [imagej/imagej-omero#95]
Trying to open an SVS file. Example file can be found at http://downloads.openmicroscopy.org/images/SVS/

```
[ERROR] Module threw exception
java.lang.IllegalArgumentException: Dimensions (width=96999 height=45667) are too large
	at java.awt.image.SampleModel.<init>(SampleModel.java:130)
	at java.awt.image.SinglePixelPackedSampleModel.<init>(SinglePixelPackedSampleModel.java:144)
	at java.awt.image.SinglePixelPackedSampleModel.<init>(SinglePixelPackedSampleModel.java:110)
	at java.awt.image.SinglePixelPackedSampleModel.createCompatibleSampleModel(SinglePixelPackedSampleModel.java:219)
	at net.imglib2.display.screenimage.awt.ARGBScreenImage.<init>(ARGBScreenImage.java:91)
	at net.imglib2.display.screenimage.awt.ARGBScreenImage.<init>(ARGBScreenImage.java:68)
	at net.imagej.display.DefaultDatasetView.rebuild(DefaultDatasetView.java:397)
	at net.imagej.display.DefaultImageDisplay.rebuild(DefaultImageDisplay.java:136)
	at net.imagej.display.DefaultImageDisplay.display(DefaultImageDisplay.java:274)
	at org.scijava.display.DefaultDisplayService.createDisplayQuietly(DefaultDisplayService.java:231)
	at org.scijava.display.DefaultDisplayService.createDisplay(DefaultDisplayService.java:213)
	at org.scijava.display.DisplayPostprocessor.handleOutput(DisplayPostprocessor.java:123)
	at org.scijava.display.DisplayPostprocessor.process(DisplayPostprocessor.java:74)
	at org.scijava.module.ModuleRunner.postProcess(ModuleRunner.java:117)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:177)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ctrueden** [comment]
It's a general limitation of the standard image viewers of IJ1 and IJ2. One solution could be to change the ImageJ2 image display mechanism to use the BigDataViewer, either always by default, or contingently when the plane size is large.
