### ISSUE TITLE
Dicom with z-sections

### ISSUE THREAD

**Issue by jburel** [imagej/imagej-omero#99]
Tried to open a Dicom file with 32 planes and one timepoint
 ```
 [ERROR] Module threw exception
 java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Could not open a plane for the given dimensions
 	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:32)
 	at net.imglib2.img.cell.LazyCellImg$LazyCells.get(LazyCellImg.java:104)
 	at net.imglib2.img.list.AbstractLongListImg$LongListCursor.get(AbstractLongListImg.java:98)
 	at net.imglib2.img.cell.CellCursor.getCell(CellCursor.java:94)
 	at net.imglib2.img.cell.CellCursor.moveToNextCell(CellCursor.java:182)
 	at net.imglib2.img.cell.CellCursor.reset(CellCursor.java:152)
 	at net.imglib2.img.cell.CellCursor.<init>(CellCursor.java:88)
 	at net.imglib2.img.cell.AbstractCellImg.cursor(AbstractCellImg.java:92)
 	at net.imglib2.img.cell.AbstractCellImg.cursor(AbstractCellImg.java:51)
 	at net.imglib2.img.AbstractImg.firstElement(AbstractImg.java:81)
 	at net.imagej.ImgPlus.firstElement(ImgPlus.java:276)
 	at net.imagej.DefaultDataset.getType(DefaultDataset.java:220)
 	at net.imagej.DefaultDataset.isSigned(DefaultDataset.java:225)
 	at net.imagej.DefaultDataset.mergedColorCompatible(DefaultDataset.java:704)
 	at net.imagej.DefaultDataset.<init>(DefaultDataset.java:101)
 	at net.imagej.DefaultDatasetService.create(DefaultDatasetService.java:200)
 	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:128)
 	at net.imagej.omero.DefaultOMEROService.downloadImage(DefaultOMEROService.java:515)
 	at net.imagej.omero.commands.OpenFromOMERO.run(OpenFromOMERO.java:91)
 	at org.scijava.command.CommandModule.run(CommandModule.java:199)
 	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
 	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 	at java.lang.Thread.run(Thread.java:745)
 Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Could not open a plane for the given dimensions
 	at net.imglib2.cache.ref.SoftRefLoaderRemoverCache.get(SoftRefLoaderRemoverCache.java:168)
 	at net.imglib2.cache.util.LoaderRemoverCacheAsLoaderCacheAdapter.get(LoaderRemoverCacheAsLoaderCacheAdapter.java:37)
 	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:30)
 	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:28)
 ```
 
 
Files can be found at
https://zenodo.org/record/16956#.Wt-UNtPwbdc

**Comment by ctrueden** [comment]
I cannot reproduce this bug with the linked DICOM images. Here is what I tried:

1. Downloaded the ZIP
2. Tried to import the ZIP via OMERO.insight; was told it is an unsupported format.
3. Unpacked the ZIP to its folder structure.
4. Added the folder to OMERO.insight importer; it imported 143 images into OMERO.
5. Tried opening "MR000000 [Series 0]" (256 x 256 uint16 image with 5 Z sections); it worked.

Which DICOM file failed to open for you, @jburel? Or did I import the data incorrectly to OMERO?
